### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XuXu23** [sabo10o29/MMM-TimeTreeEvent#12]
Hi.

I have a problem with the TimeTreeEvent. MagicMirror starts but the TimeTree Module isnt working.
Here ist the Code that shows up.

[06.01.2022 16:44.52.976] [ERROR] Whoops! There was an uncaught exception...
[06.01.2022 16:44.52.982] [ERROR] ReferenceError: Log is not defined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-TimeTreeEvent/node_helper.js:30:5)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Can you please help me? Thank you very much

**Comment by sabo10o29** [comment]
I apologize for the very late response.
Could you please try with the latest release?  I removed the code and fixed any bugs.
